package com.ashish.clubs.common.models.shared;

/**
 * Defines a standardized set of event types that can be published or consumed
 * across different microservices, typically via Kafka.
 */
public enum EventType {
    // User Events
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ROLE_ASSIGNED,
    USER_PROFILE_UPDATED,

    // Club Events
    CLUB_CREATED,
    CLUB_UPDATED,
    CLUB_DELETED,
    CLUB_MEMBERSHIP_REQUESTED,
    CLUB_MEMBERSHIP_APPROVED,
    CLUB_MEMBERSHIP_REJECTED,
    CLUB_MEMBER_LEFT,
    CLUB_MEMBER_BANNED,

    // Feed Events
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_LIKED,
    POST_UNLIKED,
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    // Event/Promotion Events
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    PROMOTION_CREATED,
    PROMOTION_UPDATED,
    PROMOTION_DELETED,

    // Media Events
    MEDIA_UPLOADED,
    MEDIA_DELETED,

    // Notification Events (these might be generated by other services to trigger notifications)
    NOTIFICATION_TRIGGERED, // Generic notification trigger

    // Analytics Events (if you want to send raw usage data to analytics service)
    PAGE_VIEWED,
    BUTTON_CLICKED,
    // etc.

    UNKNOWN // Fallback for undefined event types
}
